name: ArgoCD

on:
  workflow_dispatch:

jobs:
  deploy_argocd:
    runs-on: self-hosted
    steps:
      - name: Install kubectl
        run: |
          sudo apt-get update && sudo apt-get install -y apt-transport-https gnupg
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo apt-get update
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      - name: Create namespace argocd
        run: |
         if kubectl get namespace argocd &> /dev/null; then
         echo "Namespace argocd already exists, skipping creation."
         else
         kubectl create namespace argocd
         fi

      - name: Apply Argo CD manifests
        run: kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

      - name: Apply ArgoCD manifests
        run: kubectl patch svc argocd-server -n argocd -p '{"spec":{"type":"LoadBalancer"}}'

      - name: Patch ArgoCD service type
        run: kubectl patch svc argocd-server -n argocd --type='json' -p='[{"op":"replace","path":"/spec/type","value":"LoadBalancer"}]'

      - name: Wait for outputs
        run: sleep 30

      - name: Retrieve ArgoCD admin password
        run: kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo
